name: Bug report
description: Report a problem with the repo or tooling
labels: ["type:bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of the bug.
      placeholder: Tell us what you saw...
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Minimal steps so we can reproduce the issue.
      placeholder: "1. ...\n2. ...\n3. ..."
  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      description: Paste any error logs or screenshots.
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: OS, Python, ffmpeg, exiftool versions
